# Uncomment this line to define a global platform for your project
# platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # permission_handler：开启需要的权限宏（只开启用到的即可）
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar（日历 / 日程）
        # 'PERMISSION_EVENTS=1',

        ## dart: PermissionGroup.reminders（提醒事项）
        # 'PERMISSION_REMINDERS=1',

        ## dart: PermissionGroup.contacts（通讯录）
        # 'PERMISSION_CONTACTS=1',

        ## dart: PermissionGroup.camera（相机）
        'PERMISSION_CAMERA=1',

        ## dart: PermissionGroup.microphone（麦克风 / 录音）
        'PERMISSION_MICROPHONE=1',

        ## dart: PermissionGroup.speech（语音识别）
        # 'PERMISSION_SPEECH_RECOGNIZER=1',

        ## dart: PermissionGroup.photos（相册 / 图片库）
        'PERMISSION_PHOTOS=1',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]（定位：使用期间/始终）
        'PERMISSION_LOCATION=1',

        ## dart: PermissionGroup.notification（通知）
        'PERMISSION_NOTIFICATIONS=1',

        ## dart: PermissionGroup.mediaLibrary（媒体资料库 / Apple Music）
        # 'PERMISSION_MEDIA_LIBRARY=1',

        ## dart: PermissionGroup.sensors（传感器：加速度计/陀螺仪等）
        # 'PERMISSION_SENSORS=1',

        ## dart: PermissionGroup.bluetooth（蓝牙）
        # 'PERMISSION_BLUETOOTH=1',

        ## dart: PermissionGroup.appTrackingTransparency（App 跟踪透明度 / IDFA）
        # 'PERMISSION_APP_TRACKING_TRANSPARENCY=1',

        ## dart: PermissionGroup.criticalAlerts（关键通知）
        # 'PERMISSION_CRITICAL_ALERTS=1'
      ]
    end
  end
end
